---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-demo
spec:
  selector:
    matchLabels:
      app: api-demo
  replicas: 2
  template:
    metadata:
      labels:
        app: api-demo
    spec:
      containers:
        - name: api-demo
          image: api-demo
          ports:
            - containerPort: 3000

---

apiVersion: v1
kind: Service
metadata:
  name: api-demo
  labels:
    app: api-demo
spec:
  type: LoadBalancer  # Add this line to make it a load balancer
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 3000
  selector:
    app: api-demo
